### ISSUE TITLE
Where to start?

### ISSUE THREAD

**Issue by evolvio4all** [evolvio4all/evolvio4Java#1]
What are the first few things we need to do?
Some ideas:
What build tool to use? Maven? Gradle?
Which UI tool to use? Swing? JavaFX?
How will it be run? From the IDE? From Command line? From an executable jar?

**Comment by evolvio4all** [comment]
Vote for Maven here

**Comment by evolvio4all** [comment]
My vote goes to Maven, Swing and an executable jar

**Comment by ghost** [comment]
My vote goes to Maven, Swing and an Executable Jar

**Comment by Holkin** [comment]
Maven, Spring boot, Processing

**Comment by quete12** [comment]
If you have a look at the processing source code you'll see that there is not very much added to the default java.awt or swing elements, it may even cause some Preformance Issues (all the float Math functions only pass those values to the default java Math functions and cast the result to float...)

So I'd recomend to use Maven with Swing. Java FX is quite powerfull but I feel like it's a bit messed up for "game" development. 

IMO it doesn't really matter how we are going to render things and what frameworks we use, as long as we split the represenation layer from the logic layer. The benefit of separating the logic and representation is that we can use the same modules for a Client Program and for a (maybe one day) server based program... - wouldn't it be cool if everyone could train their AI and let them all live on a central world -

**Comment by ghost** [comment]
There's already a repo for [Processing here](https://github.com/evolvio4all/evolvio4Processing)
Spring Boot is an interesting idea although am not sure whether making it a web app is the right direction

**Comment by ghost** [comment]
Yeah definitely gotta split up the rendering and logic! Any pattern you recommend... MVC? MVVM? MPV?

**Comment by quete12** [comment]
I'm used to MVC in Business apps but games ... in the end it will be a variation of it. 

I thought about something like a ComponentRenderer structure.

But I'm not shure how the Mapping from Component to Renderer should look like
```java
public interface ComponentRenderer {
     public void render(Component component);
}

public abstract class Component{
    private ComponentRenderer renderer;

    public ComponentRenderer getRenderer(){
        return renderer();
    }
}
```
Here we get the same issue with linking the Representation to the "ProcessObject".

Whereas here it's more an issue to create and maintain the tree:
```java
public abstract class Component{

}

public abstract class Element extends Component{
    private List<Component> components;
}

public abstract class ComponentRenderer{
    private Map<Class extends Component, ComponentRenderer> childRenderers;

   protected abstract void renderThis(Component c);

   public final void render(Component c){
       renderThis(c);
       if(!(c instanceof Element)){
           return; // no sub components to render
       }
       for(Component comp : ((Element) c).getComponents()){
           ComponentRenderer renderer = childRenderers.get(comp.getClass());
           if(renderer == null){
               continue; // ignore this component
           }
           renderer.render(comp);
       }
   }
}
```

In that way we get a completely independent RendererTree. But also brings us the Pain to create a RendererClass for every ComponentClass we want to display and to maintain not only the Component Tree but also the Renderer Tree.

The "double Tree Option" lets us also add another Tree for handling updates later.

Something that's also worth mentioning: Do we want to support scripting (LUA, js, ...)?

And now we are starting to create our own Engine :anguished:

P.S: do not try to Compile this code, just wrote it on my mobile ... maybe there are lots of typos in it as well

**Comment by ghost** [comment]
Some good ideas there! Think the renderer map could be pulled out into it's own RendererMap class with a

`<T> void addRenderer(Class<? extends T> renderedClass, IRenderer<T> renderer){}`

method and a

`void render(Object rendered){}`

method. That way it could be reused for whatever component without needing to extend from ComponentRenderer

**Comment by ghost** [comment]
The only thing then is whether the components are in charge of when they should be rendered or whether they add themselves to a Collection of things to render which is iterated over by the renderers at some later point.

**Comment by ghost** [comment]
Scripting would be nice, am not sure where it would sit within an evolution simulator though, maybe one for future ideas

**Comment by ghost** [comment]
Just added a PR for a potential starting point that uses maven, swing and an executable jar, comments welcome. Nothing rendering yet though

**Comment by quete12** [comment]
To add scripting support depends on the final goal you want to reach with this program. Maybe in the future this schould not only simulate circles floating around in a 2d space but some real evolving 3d creatures. Scripting is then used to allow an "enduser" to modify the behaviour, add new bodyparts etc without having to recompile or knowing the project in detail. A well defined and documented Interface will do the job for most scripters.
My personal goal is to use the knowledge gained here in a Simulator for cellular evolution with the goal to simulate the transition from single cell organisms to multi cell organisms.

**Comment by quete12** [comment]
For a Modeling system i propose http://sparxsystems.com/products/ea/ it is not free and no very cheap but it's extreamly powerfull for the price you pay.

**Comment by quete12** [comment]
> The only thing then is whether the components are in charge of when they should be rendered or whether they add themselves to a Collection of things to render which is iterated over by the renderers at some later point.


Do components need to be in charge of when they get rendered? I think the descision if something gets rendered should be made in the renderer based on maybe zoom and a defined near and far clip in the component.

**Comment by Holkin** [comment]
It is not required to web app to use Spring Boot.
Spring is just dependency injection framework. Nothing about web.
Spring boot just allows you to run it easily.

**Comment by Holkin** [comment]
Access denied to push.

**Comment by ghost** [comment]
I love the ideas of eventually allowing scripting and body parts and being able to choose between 2D or 3D, and making it flexible enough to simulate single/multi-celled life. It would need a pretty flexible definition of body and body part but it seems perfectly possible with the right structure in place.

I'm very hesitant to go with a paid option though, to be frank I don't want to pay for anything lol

**Comment by ghost** [comment]
Ah didn't know about Spring Boot being just a DI framework, very interesting. It seems like it would reduce a lot of boilerplate but might reduce flexibility too. It depends on how it would interact with any scripting we put in place later on. Let's keep it in mind.

**Comment by ghost** [comment]
WRT how Spring Boot might interact with any scripting data, it looks like adding a configuration class which points to a resources/scripts/ directory would work very nicely and give all the flexibility we need.

**Comment by quete12** [comment]
How do you feel about if I create the same rendering classes paralell to yours but with lwjgl?

**Comment by ghost** [comment]
Yeah that sounds good!
