### ISSUE TITLE
Question: Large Merge?

### ISSUE THREAD

**Issue by Air1N** [evolvio4all/evolvio4Java#11]
Hello! I come from the JavaScript repo, I was wondering since I seem to be the only person working on it, if a large merge would be okay? (I'm asking here because there's actually people here as far as I can tell)

**Comment by ghost** [comment]
I'd recommend against large commits as it helps to get into good habits from the start eg. by treating it as open source rather than a personal project, and by committing based on a unit of work done rather than based on time spent

**Comment by Air1N** [comment]
Alright, sounds good, I am trying to avoid it.
